org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx3G

# Done to increase the memory available to gradle.
archives_base_name=dynamic_pack_manager
modrinth_id=1DmOAPcC
curseforge_id=1118042

mod_version=3.0.0
releaseType=beta
maven_group = codes.atomys.dynamicpack

minecraft_version=26.1.2
# used only as display for players
supported_minecraft_versions=26.1.2
# used in the version creation process (.split(","))
supported_minecraft_versions_list=26.1,26.1.1,26.1.2
# which platforms are supported by the mod
platforms=fabric,neoforge

# https://fabricmc.net/develop/
fabric_loader_version=0.19.2
fabric_api_version=0.145.4+26.1.2

# https://neoforged.net
neoforge_version=26.1.2.12-beta
