org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx2g

# Done to increase the memory available to gradle.
archives_base_name=dynamic_pack_manager
modrinth_id=1DmOAPcC
curseforge_id=1118042

mod_version=2.1.0
releaseType=release
maven_group = codes.atomys.dynamicpack

minecraft_version=1.21.3
# used only as display for players
supported_minecraft_versions=1.21.x
# used in the version creation process (.split(","))
supported_minecraft_versions_list=1.21,1.21.1,1.21.2,1.21.3
# which platforms are supported by the mod
platforms=fabric,neoforge,forge

# https://parchmentmc.org/docs/getting-started
parchmentmc_minecraft_version=1.21
parchmentmc_version=2024.07.28

# https://fabricmc.net/develop/
fabric_loader_version=0.16.9
fabric_api_version=0.107.3+1.21.3

# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=53.0.11
# https://neoforged.net
neoforge_version=21.3.26-beta



